// Put the single-file build where the site is served from, web/index.html, and pin its inline
// scripts in the deployed Content-Security-Policy.
//
// The page has no external script at all, so `script-src` can name exactly the two inline
// scripts it carries (the pre-paint theme line and the app) by their sha256, and nothing else
// runs: not an injected tag, not an edited copy of the app. The hashes change with every build,
// which is why this step writes them rather than a person.
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const WEB = path.join(HERE, "..");
const built = path.join(WEB, ".build", "index.html");
let html = fs.readFileSync(built, "utf8");

// `crossorigin` means nothing on an inline script; drop it so the markup says what it does.
html = html.replace(/<script type="module" crossorigin>/g, '<script type="module">');
const banner = "<!-- GENERATED by `npm run build` in web/ from web/app/. Do not edit: change web/app/src and rebuild. -->\n";
html = banner + html;

const scripts = [...html.matchAll(/<script(?: type="module")?>([\s\S]*?)<\/script>/g)].map((m) => m[1]);
if (/<script[^>]*\bsrc=/i.test(html)) throw new Error("the built page loads an external script; the CSP below would block it");
if (scripts.length !== 2) throw new Error(`expected 2 inline scripts (theme + app), found ${scripts.length}`);
const hashes = scripts.map((s) => `'sha256-${crypto.createHash("sha256").update(s, "utf8").digest("base64")}'`);

const vpath = path.join(WEB, "vercel.json");
const vercel = JSON.parse(fs.readFileSync(vpath, "utf8"));
const csp = [
  "default-src 'self'",
  `script-src 'self' ${hashes.join(" ")}`,
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src https://fonts.gstatic.com",
  "img-src 'self' data:",
  "connect-src 'self'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "form-action 'none'",
  "object-src 'none'",
].join("; ");
let set = 0;
for (const block of vercel.headers || []) for (const h of block.headers || []) {
  if (h.key === "Content-Security-Policy") { h.value = csp; set++; }
}
if (set !== 1) throw new Error(`expected one Content-Security-Policy header in vercel.json, found ${set}`);

fs.writeFileSync(path.join(WEB, "index.html"), html);
fs.writeFileSync(vpath, JSON.stringify(vercel, null, 2) + "\n");
fs.rmSync(path.join(WEB, ".build"), { recursive: true, force: true });
console.log(`placed web/index.html (${Math.round(html.length / 1024)} KB), pinned ${hashes.length} script hashes in vercel.json`);
